=== Rnikolett/WSI08IxmlGyak/RN_1001/orarend.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="orarend">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="ora" minOccurs="0" maxOccurs="unbounded" type="oratipus">
				
			</xs:element>
		</xs:sequence>
	</xs:complexType>	
</xs:element>

<xs:complexType name="oratipus">
	<xs:sequence>
		<xs:element name="targy" type="xs:string"/>
		<xs:element name="idopont" type="idoponttipus"/>
		<xs:element name="helyszin" type="xs:string"/>
		<xs:element name="oktato" type="xs:string"/>
		<xs:element name="szak" type="xs:string"/>
	</xs:sequence>
		<xs:attribute name="id" type="xs:int" use="required"/>
		<xs:attribute name="tipus" type="oratipustipus" default="eloadas"/>
</xs:complexType>

<xs:simpleType name="oratipustipus">
	<xs:restriction base="xs:string">
	<xs:enumeration value="eloadas"/>
	<xs:enumeration value="gyakorlat"/>
	</xs:restriction>
</xs:simpleType>

<xs:complexType name="idoponttipus">
	<xs:sequence>
		<xs:element name="nap" type="naptipus"/>
		<xs:element name="kezdet" type="xs:positiveInteger"/>
		<xs:element name="vege" type="xs:positiveInteger"/>
	</xs:sequence>
</xs:complexType
>
<xs:simpleType name="naptipus">
	<xs:restriction base="xs:string">
	<xs:enumeration value="Hétfő"/>
	<xs:enumeration value="Kedd"/>
	<xs:enumeration value="Szerda"/>
	<xs:enumeration value="Csütörtök"/>
	</xs:restriction>
</xs:simpleType>



</xs:schema>

=== Rnikolett/WSI08IxmlGyak/WSI08I_1001/RN_orarend.xml
<?xml version="1.0" encoding="UTF-8"?>



<orarend xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="orarend.xsd">
	<ora id="1" tipus="eloadas">
		<targy>Mesterséges Inteligencia</targy>
		<idopont>
			<nap>Hétfő</nap>
			<kezdet>12</kezdet>
			<vege>15</vege>
		</idopont>
		<helyszin>A1/305</helyszin>
		<oktato>Dr. Dudás László</oktato>
		<szak>GE-BI</szak>
	</ora>
	
	<ora id="2" tipus="eloadas">
		<targy>Web technológiág</targy>
		<idopont>
			<nap>Hétfő</nap>
			<kezdet>15</kezdet>
			<vege>17</vege>
		</idopont>
		<helyszin>In/103</helyszin>
		<oktato>Agárdi Anita</oktato>
		<szak>GE-BI</szak>
	</ora>
	
	<ora id="2" tipus="gyakorlat">
		<targy>Web technológiák</targy>
		<idopont>
			<nap>Hétfő</nap>
			<kezdet>17</kezdet>
			<vege>19</vege>
		</idopont>
		<helyszin>In15</helyszin>
		<oktato>Sátán Ádám</oktato>
		<szak>GE-BI</szak>
	</ora>
	
	<ora id="3" tipus="eloadas">
		<targy>Webes alkalmazások(Java)</targy>
		<idopont>
			<nap>Kedd</nap>
			<kezdet>10</kezdet>
			<vege>12</vege>
		</idopont>
		<helyszin>In/103</helyszin>
		<oktato>Dr. Bednarik László</oktato>
		<szak>GE-BI</szak>
	</ora>
	
	<ora id="3" tipus="eloadas">
		<targy>Adatkezelés XML-ben</targy>
		<idopont>
			<nap>Kedd</nap>
			<kezdet>12</kezdet>
			<vege>14</vege>
		</idopont>
		<helyszin>37</helyszin>
		<oktato>Dr. Badnarik László</oktato>
		<szak>GE-BI</szak>
	</ora>
	
	<ora id="4" tipus="gyakorlat">
		<targy>Kínai</targy>
		<idopont>
			<nap>Kedd</nap>
			<kezdet>16</kezdet>
			<vege>18</vege>
		</idopont>
		<helyszin>117</helyszin>
		<oktato>Kristi Fan</oktato>
		<szak>-</szak>
	</ora>
	
	<ora id="5" tipus="eloadas">
		<targy>Szoftvertechnológia</targy>
		<idopont>
			<nap>Szerda</nap>
			<kezdet>8</kezdet>
			<vege>12</vege>
		</idopont>
		<helyszin>218</helyszin>
		<oktato>Dr. Mileff Péter</oktato>
		<szak>GE-BI</szak>
	</ora>
	
	<ora id="6" tipus="eloadas">
		<targy>Windows Rendszergazda</targy>
		<idopont>
			<nap>Szerda</nap>
			<kezdet>16</kezdet>
			<vege>20</vege>
		</idopont>
		<helyszin>112</helyszin>
		<oktato>Wagner György</oktato>
		<szak>GE-BI</szak>
	</ora>
	
	<ora id="3" tipus="gyakorlat">
		<targy>Webes alkalmazások(Java)</targy>
		<idopont>
			<nap>Csütörtök</nap>
			<kezdet>10</kezdet>
			<vege>12</vege>
		</idopont>
		<helyszin>In/202</helyszin>
		<oktato>Dr. Bednarik László</oktato>
		<szak>GE-BI</szak>
	</ora>
	
	<ora id="3" tipus="gyakorlat">
		<targy>Adatkezelés XML-ben</targy>
		<idopont>
			<nap>Csütörtök</nap>
			<kezdet>12</kezdet>
			<vege>14</vege>
		</idopont>
		<helyszin>In/102</helyszin>
		<oktato>Dr. Badnarik László</oktato>
		<szak>GE-BI</szak>
	</ora>
	
	<ora id="4" tipus="gyakorlat">
		<targy>Kínai</targy>
		<idopont>
			<nap>Csütörtök</nap>
			<kezdet>16</kezdet>
			<vege>18</vege>
		</idopont>
		<helyszin>117</helyszin>
		<oktato>Kristi Fan</oktato>
		<szak>-</szak>
	</ora>
	
	
</orarend>
